# export PATH="/usr/local/mysql/bin:/usr/local/sbin:$PATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home"
export MAVEN_OPTS="-Xms1536m -Xmx2048m"
export COMPUTERNAME=localhost
export ORACLE_HOME=/opt/oracle
export M2_HOME=/Users/sswright/.m2
#export ORACLI_HOME=$ORACLE_HOME/instantclient_11_2
export ORACLI_HOME=$ORACLE_HOME/bin
export TNS_ADMIN=$ORACLI_HOME/network/admin
#export CATALINA_HOME=/Users/xizou/dev/servers/apache-tomcat-7.0.59/
export CATALINA_HOME=/Users/sswright/dev/servers/apache-tomcat-8.5.14/
#export CATALINA_HOME=/Users/xizou/dev/servers/apache-tomcat-8.5.15/
alias sqlplus=$ORACLI_HOME/sqlplus
alias deployable="ls -1 $HOME/dev/servers/apache-tomcat-8.5.14/conf/Catalina/localhost"
export iroot="$HOME/dev/src/interact"
export ibuild="$iroot/build"
export cbuild="$iroot/common/build"
